export type UserType = {
	id : string,
    email : string,
    password : string,
    isActive : boolean,
    firstname : string,
    lastname : string,
    additionalName : string,
    profileImageUrl : string,
    backgroundImageUrl : string,
    prononus : string,
    headline : string,
    about : string,
    country : string,
    city : string,
    profileLink : string,
    Educations : Array<EducationType>,
    Experiences : Array<ExperienceType>,
}

export type EducationType = {
    id: string,
    userId: string,
    school: string,
    degree: string,
    fieldStudy: string,
    grade: string,
    activities: string,
    description: string,
    monthStartDate: string,
	monthEndDate: string,
	yearStartDate: string,
	yearEndDate: string,
}

export type ExperienceType = {
    id: string,
    userId: string,    
    employmentType: string,
    companyName: string,
    country: string,
    city: string,
    isActive: boolean,
    industry: string,
    monthStartDate: string,
	monthEndDate: string,
	yearStartDate: string,
	yearEndDate: string,    
}